apiVersion: v1
kind: Namespace
metadata:
  name: "acme-ns"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "acme-connect"
  namespace: "acme-ns"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/eks-github-irsa-role"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator
  namespace: "acme-ns"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: strimzi-controller
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: "acme-cluster"
  labels:
    app: "acme-cluster"
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
  namespace: "acme-ns"
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    image: "123456789012.dkr.ecr.us-east-2.amazonaws.com/repo/kafka:1"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      remote.log.storage.system.enable: true
      remote.log.manager.task.interval.ms: 5000
      log.retention.check.interval.ms: 10000
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.include.jmx.reporter: false
    tieredStorage:
      type: custom
      remoteStorageManager:
        className: io.aiven.kafka.tieredstorage.RemoteStorageManager
        classPath: /opt/kafka/plugins/aiven-s3-tiered-storage/*
        config:
          storage.s3.bucket.name: "kafka-bucket"
          storage.backend.class: io.aiven.kafka.tieredstorage.storage.s3.S3Storage
          storage.s3.region: "us-east-1"
          chunk.size: "52428800"
          storage.key.prefix: "acme-ns-kafka-tiered-storage/"
    metricsConfig:
      type: strimziMetricsReporter
      values:
        allowList:
          - ".*"
    template:
      pod:
        imagePullSecrets:
          - name: kafkapullsecret
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: "acme-ns"
  labels:
    strimzi.io/cluster: "acme-cluster"
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: "acme-ns"
  labels:
    strimzi.io/cluster: "acme-cluster"
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: acme-raw-topic
  namespace: acme-ns
  labels:
    strimzi.io/cluster: acme-cluster
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: acme-processed-topic
  namespace: acme-ns
  labels:
    strimzi.io/cluster: acme-cluster
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: acme-intermediate-topic
  namespace: acme-ns
  labels:
    strimzi.io/cluster: acme-cluster
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: "acme-connect"
  namespace: "acme-ns"
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.1.0
  image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/repo:kafka_connector"
  replicas: 3
  bootstrapServers: "acme-cluster-kafka-bootstrap:9093"
  tls:
    trustedCertificates:
      - secretName: "acme-cluster-cluster-ca-cert"
        pattern: "*.crt"
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  metricsConfig:
    type: strimziMetricsReporter
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  template:
    pod:
      serviceAccountName: "acme-connect"
      imagePullSecrets:
        - name: kafkapullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
  namespace: acme-ns
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: apicurio-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: acme-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio-registry
          image: quay.io/apicurio/apicurio-registry-mem:2.5.11.Final
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_LOG_LEVEL
              value: INFO
            - name: REGISTRY_UI_FEATURES_READONLY
              value: "false"
            - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
              value: "true"
            - name: REGISTRY_ENABLE_CONFLUENT_ID_API
              value: "true"
            - name: REGISTRY_CONFLUENT_COMPATIBILITY_ENABLE
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: register-avro-schema
  namespace: acme-ns
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.2.1
          command: ["sh", "-c"]
          args:
            - |
              echo 'Registering Avro schema ...'
              curl -X POST http://apicurio-registry:8080/apis/registry/v2/groups/default/artifacts \
                -H "X-Registry-ArtifactId: acme-raw-topic-value" \
                -H "Content-Type: application/json" \
                --data '{"type":"record","name":"MyRecord","fields":[{"name":"id","type":"string"},{"name":"value","type":"int"}]}'
      restartPolicy: Never