---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator
  namespace: "{{ .Values.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: strimzi-controller
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: "{{ .Values.namespace }}"
  labels:
    strimzi.io/cluster: "{{ .Values.clusterName }}"
spec:
  replicas: {{ .Values.kafka.replicas | default 3 }}
  roles: [controller]
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: "{{ .Values.namespace }}"
  labels:
    strimzi.io/cluster: "{{ .Values.clusterName }}"
spec:
  replicas: {{ .Values.kafka.replicas | default 3 }}
  roles: [broker]
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: "{{ .Values.clusterName }}"
  labels:
    app: "{{ .Values.clusterName }}"
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
  namespace: "{{ .Values.namespace }}"
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    image: "{{ .Values.kafka.image | default .Values.kafkaImage }}"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      remote.log.storage.system.enable: true
      remote.log.manager.task.interval.ms: 5000
      log.retention.check.interval.ms: 10000
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.include.jmx.reporter: false
    tieredStorage:
      type: custom
      remoteStorageManager:
        className: io.aiven.kafka.tieredstorage.RemoteStorageManager
        classPath: /opt/kafka/plugins/aiven-s3-tiered-storage/*
        config:
          storage.s3.bucket.name: "{{ .Values.s3.bucketName | default .Values.bucketName }}"
          storage.backend.class: io.aiven.kafka.tieredstorage.storage.s3.S3Storage
          storage.s3.region: "{{ .Values.s3.region | default .Values.s3Region }}"
          chunk.size: "52428800"
          storage.key.prefix: "{{ .Values.namespace }}-kafka-tiered-storage/"
    metricsConfig:
      type: strimziMetricsReporter
      values:
        allowList:
          - ".*"
    template:
      pod:
        serviceAccountName: "{{ .Values.clientName }}-connect"
        imagePullSecrets:
          - name: kafka-pull-secret
  entityOperator:
    topicOperator: {}
    userOperator: {}