{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  {{- if .config }}
  config:
    {{- range $key, $val := .config }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
{{- end }}